services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://banktt.onrender.com
      - key: L5_SWAGGER_CONST_HOST
        value: https://banktt.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        value: postgresql://test_0lal_user:09PRDnmv5eFcmYdfpJCvcPNuRCRAwwPd@dpg-d42jr1mr433s73dne95g-a.oregon-postgres.render.com/test_0lal